import RegisterPageView from "@/components/pageViews/Register";
import WithNavbarTemplate from "@/components/templates/WithHeaderNavbar";
import { NextPageWithTemplate } from "@/types";
import Head from "next/head";
import React from "react";

const Register: NextPageWithTemplate = () => {
  return (
    <>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <RegisterPageView />
    </>
  );
};

// Same as Next.js layout component.
// The name is changed from 'layout' to `template` for the sake of Atomic Design.
// SEE: https://nextjs.org/docs/basic-features/layouts
Register.getTemplate = (page: React.ReactElement) => {
  return <WithNavbarTemplate>{page}</WithNavbarTemplate>;
};

export default Register;
